[package]
name = "pbrt"
version = "0.1.0"
edition = "2024"

[dependencies]
num-traits = "0.2.19"

[dependencies.windows]
version = "0.62.2"
features = ["Win32_Foundation","Win32_Graphics_Gdi","Win32_System_LibraryLoader","Win32_UI_WindowsAndMessaging"]
